"""Add health_conditions and taste_preferences to UserProfile

Revision ID: e4db6d4c00db
Revises: 798805b7999b
Create Date: 2026-07-14 07:17:00.512839+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4db6d4c00db'
down_revision: Union[str, None] = '798805b7999b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('health_conditions', sa.String(length=500), nullable=True))
    op.add_column('user_profiles', sa.Column('taste_preferences', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'taste_preferences')
    op.drop_column('user_profiles', 'health_conditions')
    # ### end Alembic commands ###
